### ISSUE TITLE
[FIX]: Correct the links to sample files in README.md

### ISSUE THREAD

**Issue by mohiwalla** [mohiwalla/dtquick#3]
After changing the file names in `Samples/` folder the links in `README.md` file are now not in working condition and getting a **404 Error** due to that. So, fix the links in README.md file.

![image](https://github.com/mohiwalla/dtquick/assets/121000462/c5f082e0-8030-410e-9266-0617eba0a709)

# Happy Hacking

**Comment by Anemaygi** [comment]
Hi, can you assign this issue to me? Thank you :)

**Comment by kliu57** [comment]
I can do this fix. Can you assign it to me?

**Comment by Virtual4087** [comment]
assign me

**Comment by mohiwalla** [comment]
Hi, @Virtual4087 and @kliu57 I've accepted the first ever PR. You are always welcome to create any new valid issue, I'd assign that to you directly. Happy Hacking 😄🤞

**Comment by mohiwalla** [comment]
Thanks @codewithsonyy for your contribution.
